### ISSUE TITLE
two new questions

### ISSUE THREAD

**Issue by Choicelin** [okoala/koa-jwt2#2]
1.Does koa-jwt2 have an expiry time and can I set this time?
2.How can I send token to client through my login api, this token used to verify  in koa-jwt2's getToken function?

I have read your document several times, I didn't find the answer to the above question,could you please explain some for me,? thanks!

**Comment by okoala** [comment]
@Choicelin 
1. You should read jsonwebtoken document: https://github.com/auth0/node-jsonwebtoken
2. verifiy token, you can read here https://github.com/okoala/koa-jwt2/blob/master/lib/index.js#L115
3. token is only a normal object,  use `ctx.body` can send to client.

**Comment by Choicelin** [comment]
@okoala thank you very much!
